### ISSUE TITLE
Redis Exporter not supporting Redis Cluster

### ISSUE THREAD

**Issue by anandarivu** [camunda-community-hub/zeebe-redis-exporter#105]
Does Zeebe Redis exported support connecting to redis in cluster mode in AWS? We are getting an error as below

2024-02-05T13:25:21.802Z ERROR 1 --- [ol-811-thread-1] io.zeebe.redis.connect.java.ZeebeRedis   : Consumer[group=simple-monitor, id=ea94a222-bda2-42a9-8757-064bae812f3c] failed to read from streams 'zeebe:*': CROSSSLOT Keys in request don't hash to the same slot. Initiating reconnect.

**Comment by VonDerBeck** [comment]
@anandarivu:
Until now we haven't done anything special for the cluster mode. So the answer to "is this currently supported" might be no. Of course we have the intention to support a broad range of setups with the Redis Exporter and the provided connector.

In order to solve this - can you answer the following questions:
- can you give me some hints on how your setup / architecture looks like?
- does exporting events in Zeebe work seamlessly without errors?
- what does your connection string on the receiver / connector side look like?

There are typically several ways to resolve the issue. Before doing so I would like to narrow down the cause. I suspect that the connector, which reads from several streams simultaneously, is the main cause. But guessing and knowing are 2 different things.

Thanks in advance for your help!
Gunnar

**Comment by VonDerBeck** [comment]
I've had a rough look at it in the meantime:

The ability to deal with Redis clusters requires several steps:

1. Ability to use a Lettuce-RedisClusterClient instead of the "normal" RedisClient. The abstraction in the underlying Lettuce framework is not quite optimal, so there is already some work to be done here. It is interesting that the normal RedisClient already works when using the AWS ElasticCache Redis cluster to the extent that it only complains with "CROSSSLOT Keys in request don't hash to the same slot". I would have expected a different error message in an earlier phase. Amazon also refers to the RedisClusterClient. So this is the most basic requirement.
2. Deailing with "CROSSSLOT Keys in request don't hash to the same slot." This could already work with a tuned prefix to the extent that all records then end up in the same slot and can therefore all be retrieved collectively as before by using a Multi-key Operation. Even if this does not necessarily correspond to the purpose of a cluster it would enable its use.
3. Efficient distribution of the records in the cluster and expansion of the connector in such a way that it can also handle multiple slots. This is the real challenge. Multi-key operations are not possible in the cluster, so intelligent distribution should take place here, which can be used in the connector without too much work.

I have marked the issue as an enhancement-

**Comment by anandarivu** [comment]
Thanks @VonDerBeck. We too proceeded to by wrapping prefix "zeebe" with "{}". Though this modification defeats the actual purpose of cluster, we really do not have any other option as of now.

Will eagerly wait for the enhancement to be implemented. Thanks for your prompt response

**Comment by VonDerBeck** [comment]
Hi @anandarivu,
I just released version 0.9.10 of the exporter and connector with basic cluster support. There is already a corresponding [pull request for Zeebe Simple Monitor](https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/674) using the new functionality. For details about the configuration please see the README of this project (there is a new section for Redis clusters).

As it is impossible for me to test all possible cluster setups and configurations, I would be most grateful for your feedback on whether export & import is now possible with your AWS ElasticCache Redis cluster as well. 

Thanks in advance!
Gunnar

**Comment by VonDerBeck** [comment]
Solved with 0.9.10
